version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USERNAME: postgres
      POSTGRES_PASSWORD: admin
      PG_NAME: helicopters

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
