version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: helicopters
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  test_db:
    image: postgres
    environment:
      POSTGRES_DB: test_helicopters
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - '5433:5432'
