version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: helicopters
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  test_2:
    image: postgres
    environment:
      POSTGRES_DB: test_helicopters_2
      POSTGRES_USER: test_user_2
      POSTGRES_PASSWORD: test_pass_2
    ports:
      - '5434:5432'
