version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: helicopters
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
